package com.efir.main.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Use an autogenerated ID for the entity

    @Column(nullable = false)
    private String name;

    @Column(unique = true, nullable = false)
    private String uniqueUserId;

    private String role;

    @Column(nullable = false)
    private String mobile;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private String password;

    @OneToMany(mappedBy = "filedBy")
    private List<Complaint> filedComplaints;

}